setwd("~/R/hpcdata")
hpcdata <- read.table(pipe('findstr /B /R ^[1-2]/2/2007 household_power_consumption.txt'),header=F, sep=';', na.strings="?", stringsAsFactors = F)
colnames(hpcdata) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
png(file = "plot2.png", width = 480, height = 480)
with(hpcdata, plot(1:nrow(hpcdata), Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab="", axes=F))
axis(side=1, at=c(0, 1441, 2880), labels=c("Thu", "Fri", "Sat"))
axis(side=2, at=seq(0, 10, by=2), labels=seq(0, 10, by=2))
box()
dev.off()
