setwd("~/R/hpcdata")
hpcdata <- read.table(pipe('findstr /B /R ^[1-2]/2/2007 household_power_consumption.txt'),header=F, sep=';', na.strings="?", stringsAsFactors = F)
colnames(hpcdata) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
png(file = "plot1.png", width = 480, height = 480)
with(hpcdata, hist(Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kiloWatts)"))
dev.off()