setwd("~/R/hpcdata")
hpcdata <- read.table(pipe('findstr /B /R ^[1-2]/2/2007 household_power_consumption.txt'),header=F, sep=';', na.strings="?", stringsAsFactors = F)
colnames(hpcdata) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
png(file = "plot3.png", width = 480, height = 480)
with(hpcdata, plot(1:nrow(hpcdata), Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab="", axes=F))
with(hpcdata, lines(Sub_metering_2, type = "l", col="red"))
with(hpcdata, lines(Sub_metering_3, type = "l", col="blue"))
axis(side=1, at=c(0, 1441, 2880), labels=c("Thu", "Fri", "Sat"))
axis(side=2, at=seq(0, 50, by=10), labels=seq(0, 50, by=10))
box()
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
legend("topright", labels, lwd=c(1,1,1), col = c("black", "red", "blue"))
dev.off()
